# Release: https://github.com/scrtlabs/cintara-node-llm-bridge/releases/tag/v0.0.13
# Workflow URL: https://github.com/scrtlabs/cintara-node-llm-bridge/actions/runs/17261848666
# Commit: https://github.com/scrtlabs/cintara-node-llm-bridge/commit/6c2e3f1c78d1e08f721a3d905e5ccc0adb87b1c2
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/cintara-node-llm-bridge@sha256:0a7399c1bc699fdb5b589b74002db8cdf7d4b88844225c0091f6099b17a61495
    ports:
      - '26656'
      - '26657'
